INSERT INTO `restaurants` VALUES (7,"Heirloom Cafe","3.3","34, Fakkir Sahib Street, 3rd Ln, Triplicane, Chennai - 600005");
INSERT INTO `restaurants` VALUES (8,"Planet of the Grapes","4.0","Taj Coromandel, 37, Uthamar Gandhi Road, Tirumurthy Nagar, Nungambakkam, Chennai - 600034");
INSERT INTO `restaurants` VALUES (9,"Rich Table","3.6","Binny Rd, Anna Salai, Chennai - 600002");
INSERT INTO `restaurants` VALUES (10,"Montana Restaurant","4.6","40, Old #71-A, B Ramachandra Adithanar Road, Gandhi Nagar, Adyar, Chennai - 600020");
INSERT INTO `restaurants` VALUES (11,"California Pizza Kitchen","3.5","18, LV Prasad Rd, Thangal karai, Dhanalakshmi Colony, Vadapalani, Chennai - 600026");
INSERT INTO `restaurants` VALUES (12,"Lord of the Fries","3.5","Rathri Bazzar, Little Mount, Guindy, Chennai - 600032");
INSERT INTO `restaurants` VALUES (13,"Mama's Fish House","4.1","Mahatma Gandhi, Anna Salai, Chennai - 600034");
INSERT INTO `restaurants` VALUES (14,"Eatmore Fried Chicken","3.6","31, Mannady Street, Muthialpet, George Town, Chennai - 600001");
INSERT INTO `restaurants` VALUES (15,"The Lady & Sons","4.7","102/82, G.N. Chetty Road, Parthasarathi Puram, T. Nagar, Chennai - 600017");
INSERT INTO `restaurants` VALUES (16,"Chez Panisse Cafe","3.6","Rathri Bazzar, Little Mount, Guindy, Chennai - 600032");
INSERT INTO `restaurants` VALUES (17,"Spago","3.6","18, LV Prasad Rd, Thangal karai, Dhanalakshmi Colony, Vadapalani, Chennai - 600026");
INSERT INTO `restaurants` VALUES (18,"Chipotle Mexican Grill","4.2","Rathri Bazzar, Little Mount, Guindy, Chennai - 600032");
INSERT INTO `restaurants` VALUES (19,"Burgrill Wasabi by Morimoto","3.7","9, College Road, Nungambakkam, Chennai - 600006");
INSERT INTO `restaurants` VALUES (20,"The Gourmet Kitchen","4.8","2nd Floor, Kuppuswamy Street,Gopathi Narayanaswami Chetty Rd, T. Nagar, Chennai - 600017");
INSERT INTO `restaurants` VALUES (21,"Vintage Machine","3.7","40, Old #71-A, B Ramachandra Adithanar Road, Gandhi Nagar, Adyar, Chennai - 600020");
INSERT INTO `restaurants` VALUES (22,"Pine & Dine","4.3","No. 21, Greams Road, opposite MRF Building, Thousand Lights East, Chennai - 600006");
INSERT INTO `restaurants` VALUES (23,"Banana Leaf","3.7","102/82, G.N. Chetty Road, Parthasarathi Puram, T. Nagar, Chennai - 600017");
INSERT INTO `restaurants` VALUES (24,"A Salt & Battery","4.9","Crowne Plaza Chennai Adyar Park, 132, TTK Road, Chennai - 600018");
INSERT INTO `restaurants` VALUES (25,"Dinner in the Sky","3.7","No. 21, Greams Road, opposite MRF Building, Thousand Lights East, Chennai - 600006");
INSERT INTO `restaurants` VALUES (26,"Steam Plant","3.8","34, Fakkir Sahib Street, 3rd Ln, Triplicane, Chennai - 600005");
INSERT INTO `restaurants` VALUES (27,"The Lockhart","4.4","Rathri Bazzar, No.63, Anna Salai, Guindy, Chennai - 600032");
INSERT INTO `restaurants` VALUES (28,"Tongabezi Lodge","3.8","146, TT Krishnamachari Rd, Cooperative Colony, Sri Ram Nagar, Alwarpet, Chennai - 600018");
INSERT INTO `restaurants` VALUES (29,"Tommy Guns Garage","4.0","1st Floor, Kuppuswamy Street,Gopathi Narayanaswami Chetty Rd, T. Nagar, Chennai - 600017");
INSERT INTO `restaurants` VALUES (30,"Fruce","3.8","Crowne Plaza Chennai Adyar Park, 132, TTK Road, Chennai - 600018");
INSERT INTO `restaurants` VALUES (31,"Nacho Daddy","3.9","2nd, 3rd Tower Victorie, 45, Gopathi Narayanaswami Chetty Rd, T. Nagar, Chennai - 600017");
INSERT INTO `restaurants` VALUES (32,"Momo Jojo","4.5","39, College Road, Nungambakkam, Chennai - 600006");
INSERT INTO `restaurants` VALUES (33,"Dough Doughnuts","3.8","No.6, Mayor Ramanathan Salai, Spur Tank road, Chetpet, Chennai - 600031");
